Repository owncloud/user_ldap, pull requests merged in 2018-11, with the labels that each got.

#302 Add more tests to drone
  .drone.yml
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#303 Release 0.12.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - To Review

#301 failOnWarning="true"
  tests/unit/phpunit.xml
Labels: 3 - To Review

#304 Delete .travis.yml file as tests are now in drone
  .travis.yml
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#309 only start mysql server when needed
  .drone.yml
Labels: 3 - To Review, QA-team

#311 Adjust acceptance test steps changed in core
  tests/acceptance/features/webUIUserLDAP/groupMembership.feature
  tests/acceptance/features/webUIUserLDAP/paging.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#314 Fix steps changed in core
  tests/acceptance/features/webUIUserLDAP/groupMembership.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#319 Set max version to 10 for Semver
  appinfo/info.xml
Labels: 3 - To Review
