Repository owncloud/user_ldap, pull requests merged in 2018-08, with the labels that each got.

#263 fix behat extensions use
  tests/acceptance/config/behat.yml
Labels: 3 - To Review

#264 always use occ by testing app
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/UserLdapGeneralContext.php
Labels: 3 - To Review

#267 Remove unneeded SKELETON_DIR in .drone.yml
  .drone.yml
Labels: 2 - Developing

#265 run core api tests
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/config/ldap-users.ldif
Labels: 3 - To Review, QA-team

#275 Be consistent in acceptance test steps 'when the administrator'
  tests/acceptance/features/bootstrap/UserLdapGeneralContext.php
  tests/acceptance/features/bootstrap/UserLdapUsersContext.php
  tests/acceptance/features/webUIUserLDAP/avatar.feature
  tests/acceptance/features/webUIUserLDAP/changingDisplayName.feature
  tests/acceptance/features/webUIUserLDAP/changingPassword.feature
  tests/acceptance/features/webUIUserLDAP/groupMembership.feature
  tests/acceptance/features/webUIUserLDAP/loginUsingEmailAddress.feature
  tests/acceptance/features/webUIUserLDAP/paging.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#281 use mysql 5.7 in CI
  .drone.yml
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#280 Php72 drone
  .drone.yml
Labels: 3 - To Review, QA-team
