Repository owncloud/user_ldap, pull requests merged in 2018-10, with the labels that each got.

#288 Update Behat contexts needed for core acceptance tests
  tests/acceptance/config/behat.yml
  tests/acceptance/config/ldap-users.ldif
  tests/acceptance/features/webUIUserLDAP/avatar.feature
  tests/acceptance/features/webUIUserLDAP/changingDisplayName.feature
  tests/acceptance/features/webUIUserLDAP/groupMembership.feature
  tests/acceptance/features/webUIUserLDAP/loginUsingEmailAddress.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#290 Test refactor 20181004
  tests/acceptance/features/bootstrap/UserLdapGeneralContext.php
  tests/acceptance/features/webUIUserLDAP/avatar.feature
  tests/acceptance/features/webUIUserLDAP/changingDisplayName.feature
  tests/acceptance/features/webUIUserLDAP/changingPassword.feature
  tests/acceptance/features/webUIUserLDAP/groupMembership.feature
  tests/acceptance/features/webUIUserLDAP/loginUsingEmailAddress.feature
  tests/acceptance/features/webUIUserLDAP/paging.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#254 add samaccountname to session
  appinfo/info.xml
  lib/Configuration.php
  lib/Connection.php
  lib/User/Manager.php
  lib/User/UserEntry.php
  lib/User_LDAP.php
  lib/User_Proxy.php
  tests/unit/CommandTest.php
  tests/unit/User/UserEntryTest.php
Labels: 2 - Developing

#293 Update changelog post 0.11.0
  CHANGELOG.md
Labels: 3 - To Review

#237 Jump over invalid quota message if quota isn't provided
  lib/User/UserEntry.php
Labels: 4 - To release

#297 update release branch max-version to 11.0.0.0
  appinfo/info.xml
Labels: 3 - To Review, QA-team

#295 Bump max-version to 11.0.0.0
  appinfo/info.xml
Labels: 3 - To Review, QA-team
