Repository owncloud/user_ldap, pull requests merged in 2018-06, with the labels that each got.

#249 Tell groupMembership auto-complete test about the groups that exist
  tests/acceptance/features/webUIUserLDAP/groupMembership.feature
Labels: 3 - To Review, QA

#251 add phan as static code anaylser
  .drone.yml
  .phan/config.php
  Makefile
Labels: 3 - To Review

#218 Displayname nor email won't be editable from the profile page
  lib/User_LDAP.php
  lib/User_Proxy.php
Labels: 3 - To Review, blue-ticket, p2-high
