Repository owncloud/user_ldap, pull requests merged in 2018-12, with the labels that each got.

#248 Remove legacy table and resolve dn encoding issues
  appinfo/Migrations/Version20180606135121.php
  appinfo/database.xml
  appinfo/info.xml
  lib/Access.php
  lib/Command/UpdateGroup.php
  lib/Group_LDAP.php
  lib/Helper.php
  lib/ILDAPWrapper.php
  lib/Jobs/UpdateGroups.php
  lib/LDAP.php
  lib/Mapping/AbstractMapping.php
  lib/User/IUserTools.php
  lib/User/Manager.php
  lib/User/UserEntry.php
  tests/unit/AccessTest.php
  tests/unit/Group_LDAPTest.php
  tests/unit/HelperTest.php
  tests/unit/User/ManagerTest.php
Labels: 3 - To Review, blue-ticket, p2-high

#323 Release 0.13.0 changelog + VCS tweaks
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  vendor/ui-multiselect/MIT-LICENSE
  vendor/ui-multiselect/jquery.multiselect.css
  vendor/ui-multiselect/src/jquery.multiselect.js
Labels: 3 - To Review

#325 Release 0.13.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  vendor/ui-multiselect/MIT-LICENSE
  vendor/ui-multiselect/jquery.multiselect.css
  vendor/ui-multiselect/src/jquery.multiselect.js
Labels: 3 - To Review

#326 Add build status badge
  README.md
Labels: 4 - To release, QA-team

#328 Remove phar
  Makefile
Labels: 4 - To release, Drone, QA-team

#333 Fix acceptance tests
  Makefile
  tests/acceptance/features/bootstrap/bootstrap.php
Labels: 4 - To release, QA-team, dev:acceptance-tests
