Repository owncloud/user_ldap, pull requests merged in 2019-03, with the labels that each got.

#381 Add apiAuth core acceptance test suite
  .drone.yml
  tests/acceptance/config/behat.yml
Labels: 4 - To release, QA-team, dev:acceptance-tests

#188 reallow avatars to be changed if not provided by ldap
  lib/User/Manager.php
  lib/User_LDAP.php
  lib/User_Proxy.php
Labels: 2 - Developing, bug, regression, sev3-medium

#384 register CORS context
  tests/acceptance/config/behat.yml
Labels: 4 - To release, QA-team, dev:acceptance-tests

#388 Drop PHP 5.6
  .drone.yml
  appinfo/info.xml
  composer.json
  composer.lock
  tests/acceptance/config/behat.yml
  tests/acceptance/features/cliProvisioning/groups.feature
  tests/acceptance/features/webUIProvisioning/groups.feature
  vendor-bin/behat/composer.json
Labels: 4 - To release, QA-team

#392 Remove excess require-dev dependencies from composer.json
  composer.json
  composer.lock
Labels: 4 - To release, QA-team, dependencies

#394 disable integrity check because of QA tarball issue
  .drone.yml
Labels: 4 - To release, QA-team, dev:acceptance-tests

#393 Config to json
  appinfo/Migrations/Version20190315192717.php
  lib/Configuration.php
  lib/Helper.php
  tests/unit/Controller/ConfigurationControllerTest.php
Labels: 3 - To Review

#399 Remove unused use statement
  lib/Controller/MappingController.php
Labels: 3 - To Review

#400 Remove unused use statements
  lib/Connection.php
  lib/User/UserEntry.php
  tests/unit/ConnectionTest.php
  tests/unit/Controller/MappingControllerTest.php
  tests/unit/Controller/WizardControllerTest.php
Labels: 4 - To release
