Repository owncloud/user_ldap, pull requests merged in 2019-05, with the labels that each got.

#409 Store arrays as arrays, do not use newline as a separator
  appinfo/Migrations/Version20190315192717.php
  js/wizard/configModel.js
  lib/Command/TestConfig.php
  lib/Configuration.php
  lib/Connection.php
  lib/Controller/ConfigurationController.php
  lib/Wizard.php
  tests/integration/Lib/IntegrationBackupServer.php
  tests/integration/Lib/IntegrationTestBackupServer.php
  tests/unit/Controller/ConfigurationControllerTest.php
  tests/unit/WizardTest.php
Labels: 3 - To Review

#411 Email change test improvements
  tests/acceptance/features/apiProvisioningLDAP/users.feature
  tests/acceptance/features/cliProvisioning/users.feature
  tests/acceptance/features/webUIProvisioning/users.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#414 Split long-running api acceptance suites
  .drone.yml
  tests/acceptance/config/behat.yml
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#412 test quota sync with LDAP
  tests/acceptance/features/apiProvisioningLDAP/users.feature
  tests/acceptance/features/webUIProvisioning/users.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#200 check estimate to fix count when it reports the count for all users, …
  lib/Access.php
  lib/User_LDAP.php
Labels: 3 - To Review, blue-ticket, bug, enhancement, p3-medium

#415 run tests on LDAPS
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiUserLDAPConnection/backupServerConnection.feature
  tests/acceptance/features/apiUserLDAPConnection/serverConnection.feature
  tests/acceptance/features/bootstrap/UserLdapGeneralContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#416 Fix wizard by translating keys (missing code)
  js/wizard/configModel.js
Labels: 3 - To Review

#410 Kill isDefault
  lib/Configuration.php
  lib/Connection.php
Labels: 3 - To Review

#165 Reuse existing LDAP accounts if available
  lib/Access.php
  lib/User/Manager.php
  tests/acceptance/features/apiProvisioningLDAP/groups.feature
  tests/acceptance/features/apiUserLDAPConnection/groupFilter.feature
  tests/acceptance/features/webUIProvisioning/groups.feature
  tests/acceptance/features/webUIUserLDAP/groupMembership.feature
Labels: 2 - Developing, blue-ticket, p3-medium

#397 Split configuration into config and mapper
  appinfo/Migrations/Version20190315192717.php
  lib/AdminPanel.php
  lib/AppInfo/Application.php
  lib/Command/CreateEmptyConfig.php
  lib/Command/DeleteConfig.php
  lib/Command/Search.php
  lib/Command/SetConfig.php
  lib/Command/ShowConfig.php
  lib/Command/TestConfig.php
  lib/Config/Config.php
  lib/Config/ConfigMapper.php
  lib/Configuration.php
  lib/Connection.php
  lib/Controller/ConfigurationController.php
  lib/Controller/WizardController.php
  lib/Exceptions/ConfigException.php
  lib/Group_Proxy.php
  lib/Helper.php
  lib/Proxy.php
  lib/User_LDAP.php
  lib/User_Proxy.php
  lib/Wizard.php
  tests/unit/CommandTest.php
  tests/unit/ConfigurationTest.php
  tests/unit/ConnectionTest.php
  tests/unit/Controller/ConfigurationControllerTest.php
  tests/unit/Controller/WizardControllerTest.php
  tests/unit/WizardTest.php
Labels: 3 - To Review

#419 additional user/groups based tests
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiProvisioningLDAP/groups.feature
  tests/acceptance/features/apiProvisioningLDAP/users.feature
  tests/acceptance/features/apiUserLDAP/moveUser.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests
