Repository owncloud/user_ldap, pull requests merged in 2019-12, with the labels that each got.

#479 Append BEHAT_FILTER_TAGS to default tags when running core acceptance tests
  Makefile
Labels: 4 - To release, QA-team, dev:acceptance-tests

#485 Adjust tests
  .drone.starlark
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/integration/ExceptionOnLostConnection.php
  tests/unit/AccessTest.php
  tests/unit/CommandTest.php
  tests/unit/ConfigurationTest.php
  tests/unit/ConnectionTest.php
  tests/unit/Controller/ConfigurationControllerTest.php
  tests/unit/Controller/MappingControllerTest.php
  tests/unit/Controller/WizardControllerTest.php
  tests/unit/Group_LDAPTest.php
  tests/unit/User/ManagerTest.php
  tests/unit/User/UserEntryTest.php
  tests/unit/User_LDAPTest.php
  tests/unit/WizardTest.php
  vendor-bin/behat/composer.json
Labels: 3 - To Review, QA-team

#487 Add sabre/xml to behat dependencies
  .drone.starlark
  .drone.yml
  vendor-bin/behat/composer.json
Labels: 4 - To release, QA-team, dev:acceptance-tests

#489 Coding standard 2.0.0
  .drone.starlark
  tests/unit/ConnectionTest.php
  tests/unit/User/ManagerTest.php
  tests/unit/User/UserEntryTest.php
  vendor-bin/owncloud-codestyle/composer.json
Labels: 3 - To Review, QA-team

#483 Merge Back 0.15.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - To Review

#492 Add new core suites from 36629 to drone
  .drone.starlark
  .drone.yml
  tests/acceptance/config/behat.yml
Labels: 4 - To release, QA-team, dev:acceptance-tests
