Repository owncloud/user_ldap, pull requests merged in 2019-07, with the labels that each got.

#430 Remove no longer existing job from appinfo
  appinfo/info.xml
Labels: 3 - To Review

#432 Add new api share core suites
  .drone.yml
  tests/acceptance/config/behat.yml
Labels: 4 - To release, QA-team, dev:acceptance-tests

#431 split core webUI tests into two parts
  .drone.yml
  tests/acceptance/config/behat.yml
Labels: 4 - To release, QA-team, dev:acceptance-tests

#434 user_ldap app test against latest tarball
  .drone.yml
  tests/acceptance/features/webUIUserLDAP/groupMembership.feature
  tests/acceptance/features/webUIUserLDAP/loginUsingEmailAddress.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#435 Replace magic numbers with constants
  lib/ILDAPWrapper.php
  lib/LDAP.php
Labels: 3 - To Review

#436 Log bind errors
  lib/LDAP.php
Labels: 3 - To Review

#439 Add WebUIAdminSharingSettingsContext for acceptance tests
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiUserLDAPSharing/sharingLocalUserLdapUser.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests, p2-high

#437 Simplify connection: Get rid of init method
  lib/Connection.php
  tests/unit/ConnectionTest.php
Labels: 3 - To Review

#440 Revert config changes
  appinfo/Migrations/Version20190315192717.php
  js/wizard/configModel.js
  js/wizard/view.js
  js/wizard/wizardDetectorAvailableAttributes.js
  js/wizard/wizardDetectorBaseDN.js
  js/wizard/wizardDetectorFeatureAbstract.js
  js/wizard/wizardDetectorPort.js
  js/wizard/wizardDetectorSimpleRequestAbstract.js
  js/wizard/wizardDetectorTestAbstract.js
  js/wizard/wizardTabExpert.js
  lib/AdminPanel.php
  lib/AppInfo/Application.php
  lib/Command/CreateEmptyConfig.php
  lib/Command/DeleteConfig.php
  lib/Command/Search.php
  lib/Command/SetConfig.php
  lib/Command/ShowConfig.php
  lib/Command/TestConfig.php
  lib/Config/Config.php
  lib/Config/ConfigMapper.php
  lib/Configuration.php
  lib/Connection.php
  lib/Controller/ConfigurationController.php
  lib/Controller/MappingController.php
  lib/Controller/WizardController.php
  lib/Exceptions/ConfigException.php
  lib/Group_Proxy.php
  lib/Helper.php
  lib/Proxy.php
  lib/User_LDAP.php
  lib/User_Proxy.php
  lib/Wizard.php
  tests/integration/Lib/IntegrationBackupServer.php
  tests/integration/Lib/IntegrationTestBackupServer.php
  tests/unit/CommandTest.php
  tests/unit/ConfigurationTest.php
  tests/unit/ConnectionTest.php
  tests/unit/Controller/ConfigurationControllerTest.php
  tests/unit/Controller/WizardControllerTest.php
  tests/unit/WizardTest.php
Labels: 3 - To Review

#441 Add branch specific restrictions to .drone.yml
  .drone.yml
Labels: 4 - To release

#443 Remove stable10 test jobs
  .drone.yml
Labels: 4 - To release, Drone, QA-team
