Repository owncloud/user_ldap, pull requests merged in 2019-04, with the labels that each got.

#402 Standardize CI scripts
  .drone.yml
  Makefile
Labels: 3 - To Review, QA-team

#403 Adjust PHPUnit Framework namespace for PHPUnit6
  tests/unit/AccessTest.php
  tests/unit/CommandTest.php
  tests/unit/ConnectionTest.php
  tests/unit/Controller/ConfigurationControllerTest.php
  tests/unit/Controller/MappingControllerTest.php
  tests/unit/Controller/WizardControllerTest.php
  tests/unit/Group_LDAPTest.php
  tests/unit/User/ManagerTest.php
  tests/unit/User/UserEntryTest.php
  tests/unit/User_LDAPTest.php
  tests/unit/WizardTest.php
Labels: 4 - To release

#398 loginName2UserName is already called for an object, not a class
  lib/Helper.php
Labels: 4 - To release

#404 phpunit enable failOnRisky
  Makefile
  phpunit.xml
  tests/unit/AppInfo/ApplicationTest.php
  tests/unit/Controller/ConfigurationControllerTest.php
Labels: 4 - To release, QA-team

#405 Update changelog
  CHANGELOG.md
Labels: 3 - To Review

#407 Rename controller args and json keys
  js/wizard/configModel.js
  js/wizard/view.js
  js/wizard/wizardDetectorAvailableAttributes.js
  js/wizard/wizardDetectorBaseDN.js
  js/wizard/wizardDetectorFeatureAbstract.js
  js/wizard/wizardDetectorPort.js
  js/wizard/wizardDetectorSimpleRequestAbstract.js
  js/wizard/wizardDetectorTestAbstract.js
  js/wizard/wizardTabExpert.js
  lib/Controller/ConfigurationController.php
  lib/Controller/MappingController.php
  lib/Controller/WizardController.php
Labels: 3 - To Review

#408 Fix false negative result when deleting a server configuration
  lib/Helper.php
Labels: 3 - To Review
