Repository owncloud/user_ldap, pull requests merged in 2020-02, with the labels that each got.

#497 add user sync tests
  tests/acceptance/features/bootstrap/UserLdapGeneralContext.php
  tests/acceptance/features/cliProvisioning/userSync.feature
Labels: 4 - To release, QA-team

#507 Added missing core suites
  .drone.starlark
  .drone.yml
  tests/acceptance/config/behat.yml
Labels: 4 - To release, QA-team

#510 Update starlark code 20200208
  .drone.starlark
  .drone.yml
Labels: 3 - To Review, Drone, QA-team

#506 [Test_Only] Added acceptance test for single/multiple user:sync
  tests/acceptance/features/cliProvisioning/userSync.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#508 [Tests-Only] Added acceptance tests for user:sync command with super/sub-strings in user usernames
  tests/acceptance/features/cliProvisioning/userSync.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#516 Added issue tag for sync local user scenario
  tests/acceptance/features/cliProvisioning/userSync.feature
Labels: 4 - To release, QA-team

#517 [Tests-Only] Added acceptance test for user:sync with non-existing user
  tests/acceptance/features/bootstrap/UserLdapGeneralContext.php
  tests/acceptance/features/cliProvisioning/userSync.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#519 [Tests-only] Bump guzzle for testing to 6.5
  vendor-bin/behat/composer.json
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#520 [Tests-only] Run more core tests
  tests/acceptance/config/behat.yml
Labels: 4 - To release, QA-team, dev:acceptance-tests

#522 fix make clean so it cleans vendor
  Makefile
Labels: 3 - To Review, QA-team

#524 Put back zend-ldap dependency
  composer.json
Labels: 3 - To Review, QA-team, dependencies

#525 switch dependency from zendframework to laminas
  composer.json
  composer.lock
Labels: 3 - To Review, QA-team, dependencies

#521 [Tests-only] make new core tests passing
  .drone.starlark
  .drone.yml
  tests/acceptance/config/behat.yml
Labels: 4 - To release, QA-team, dev:acceptance-tests

#527 Split webUICore pipelines into more parts
  .drone.starlark
  .drone.yml
  tests/acceptance/config/behat.yml
Labels: 4 - To release, QA-team, dev:acceptance-tests

#512 Easier tls
  js/wizard/wizard.js
  js/wizard/wizardDetectorPort.js
  js/wizard/wizardTabElementary.js
  lib/Connection.php
  lib/Controller/WizardController.php
  lib/Wizard.php
  templates/part.wizard-server.php
  templates/settings.php
  tests/unit/WizardTest.php
Labels: 3 - To Review
