Repository owncloud/user_ldap, pull requests merged in 2020-06, with the labels that each got.

#573 [Tests-Only] Fix sharing step in groupMembership.feature
  tests/acceptance/features/webUIUserLDAP/groupMembership.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#575 Updating laminas/laminas-zendframework-bridge (1.0.3 => 1.0.4)
  composer.lock
Labels: 4 - To release, dependencies

#551 Reissue search in case of missing cookie in continued paged search
  lib/Access.php
  tests/integration/Lib/IntegrationTestPaging.php
  tests/integration/setup-scripts/createExplicitUsers.php
Labels: 3 - To Review, bug, regression

#579 [Tests-Only] Use openldap:1.3.0
  .drone.starlark
  .drone.yml
Labels: 4 - To release, QA-team
