Repository owncloud/user_ldap, pull requests merged in 2020-12, with the labels that each got.

#603 [Tests-Only][CI] fix the starlark code for reduced ci after merge and sonarcloud
  .drone.starlark
  .drone.yml
  .gitignore
  sonar-project.properties
Labels: 3 - To Review

#609 [tests-only] skip core app-required scenarios
  .drone.starlark
  .drone.yml
Labels: 4 - To release, QA-team

#610 [tests-only] Implement latest .drone.star as at 2020-12-22
  .drone.starlark
  .drone.yml
  phpstan.neon
  vendor-bin/behat/composer.json
  vendor-bin/php_codesniffer/composer.json
Labels: 3 - To Review, QA-team
