Repository owncloud/user_ldap, pull requests merged in 2020-07, with the labels that each got.

#582 [Tests-Only] Remove unneeded TestAlsoOnExternalUserBackend tag
  Makefile
Labels: 4 - To release, QA-team, dev:acceptance-tests

#584 [Tests-Only] only run smoke tests in CI
  .drone.starlark
  .drone.yml
Labels: 3 - To Review, Drone, dev:acceptance-tests

#587 [Tests-Only] Use latest osixia/openldap in CI
  .drone.starlark
  .drone.yml
Labels: 4 - To release, QA-team
