Repository owncloud/user_ldap, pull requests merged in 2020-04, with the labels that each got.

#541 Add scenario to check a variety of user names in LDAP
  tests/acceptance/features/apiUserLDAP/specialUsernames.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#544 Rename example-ldap-users-groups.ldif
  tests/acceptance/config/example-ldap-users-groups.ldif
Labels: 3 - To Review, QA-team

#545 Updating laminas/laminas-zendframework-bridge (1.0.2 => 1.0.3)
  composer.lock
Labels: 3 - To Review, dependencies

#546 Merge back Release 0.15.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 4 - To release

#548 [Tests-Only] Bump phan 2.7
  vendor-bin/phan/composer.json
Labels: QA-team

#553 [Tests-Only] Implement phpunit v8
  .gitignore
  tests/unit/CommandTest.php
  tests/unit/Controller/ConfigurationControllerTest.php
  tests/unit/Controller/WizardControllerTest.php
  tests/unit/Group_LDAPTest.php
  vendor-bin/behat/composer.json
  vendor-bin/phpstan/composer.json
Labels: 4 - To release, QA-team

#555 Adjust drone pipelines for PHP 7.4
  .drone.starlark
  .drone.yml
Labels: 3 - To Review, QA-team
