Repository owncloud/user_ldap, pull requests merged in 2021-11, with the labels that each got.

#694 Bump drone 20211107
  .drone.star
  vendor-bin/phan/composer.json
Labels: QA-team

#683 When checking memberof, apply the group filter after getting all groups
  lib/Group_LDAP.php
  tests/unit/Group_LDAPTest.php
Labels: 3 - To Review

#696 [Tests-Only][full-ci] enforce strict type checking in acceptace tests code
  tests/acceptance/features/bootstrap/UserLdapGeneralContext.php
  tests/acceptance/features/bootstrap/UserLdapUsersContext.php
  tests/acceptance/features/bootstrap/bootstrap.php
Labels: 3 - To Review, QA-team

#697 Users in group algos rel0160
  js/wizard/wizardTabAdvanced.js
  lib/Configuration.php
  lib/Group_LDAP.php
  templates/settings.php
Labels: 3 - To Review
